pkgdir := DirectoriesPackageLibrary( "PatternClass", "tst" );
Test( Filename( pkgdir, "chap2.tst"));
Test( Filename( pkgdir, "chap3.tst"));
Test( Filename( pkgdir, "chap4.tst"));
Test( Filename( pkgdir, "chap5.tst"));
Test( Filename( pkgdir, "chap6.tst"));
Test( Filename( pkgdir, "chap7.tst"));
Test( Filename( pkgdir, "chap8.tst"));
Test( Filename( pkgdir, "chap9.tst"));
Test( Filename( pkgdir, "chap10.tst"));
