ReadTest("chap2.tst");
ReadTest("chap3.tst");
ReadTest("chap4.tst");
ReadTest("chap5.tst");
ReadTest("chap6.tst");
ReadTest("chap7.tst");
ReadTest("chap8.tst");
ReadTest("chap9.tst");
ReadTest("chap10.tst");
